name: json2dart
description: Package to compile json to Dart code
version: 1.0.0
homepage: https://github.com/zTomz/Json2Dart

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  # lints: ^2.0.0
  # test: ^1.16.0
